source 'https://rubygems.org'

group :development do # gems used on development
  gem 'rake'
  gem 'specular'
  gem 'sonar'
  gem 'pry'
end

group :test do # gems used when testing
  gem 'rake'
  gem 'specular'
  gem 'sonar'
end

group :production do # gems used on production
end

# gems used on any environment
gem 'e'  # Espresso
gem 'el' # Espresso Lungo
gem 'thin'

gem 'enginery' # needed to run migrations
gem 'rear' # Admin interface for ActiveRecord/DataMapper/Sequel models
