source 'https://rubygems.org'

group :development do # gems used on development
  gem 'rake'
  gem 'specular'
  gem 'sonar'
  gem 'pry'
  gem 'enginery'
end

group :test do # gems used when testing
  gem 'rake'
  gem 'specular'
  gem 'sonar'
end

group :production do # gems used on production
end

# gems used on any environment
gem 'e'
gem 'e-periphery'
gem 'thin'
